[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
payra = "DCqLDvTufZiwAfK3RPeThTTdXDJBsrLxMuxyvDCqaZAR"

[program.devnet]
payra = "pAYrAkZHxebd89ojqt8pu9fBF8HWfiAcdqs8QFzk6dt"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
